import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { ApolloProvider, AppStateProvider, Web3ModalProvider } from '@/context'
import ThemeProvider from '@/theme'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'ChainSalaries',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ApolloProvider>
          <AppStateProvider>
            <ThemeProvider>
              <Web3ModalProvider>{children}</Web3ModalProvider>
            </ThemeProvider>
          </AppStateProvider>
        </ApolloProvider>
      </body>
    </html>
  )
}
